import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='bg-background text-foreground'>
      <body className='flex justify-center'>
        <div className='max-w-xl h-dvh'>{children}</div>
      </body>
    </html>
  );
}
